name: "laridae-postgres-db-schema-migrations"
description: "Reversible, zero-downtime schema migrations in PostgreSQL"
inputs:
  command:
    description: "expand/contract"
    required: true
  aws-resource-names:
    description: "Resource names in AWS output from initialization script"
    required: true
runs:
  using: composite
  steps:
    - if: ${{ inputs.command == 'sample-deploy' }}
      name: Check out application code.
      uses: actions/checkout@v4
      with:
        path: repo
    - name: Check out migration script
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          laridae_migration.json
        sparse-checkout-cone-mode: false
        path: migration_script
    - name: Checkout action scripts
      uses: actions/checkout@v4
      with:
        repository: 2308-team-8/laridae-action
        sparse-checkout: |
          scripts
        sparse-checkout-cone-mode: false
        ref: main
        path: scripts
    - name: Authenticate to AWS
      env:
        RESOURCE_NAMES: ${{ inputs.aws-resource-names }}
      run: ruby scripts/scripts/authenticate.rb
      shell: bash
    - if: ${{ inputs.command == 'expand' || }}
      name: Spin up ECS task running laridae to expand
      env:
        RESOURCE_NAMES: ${{ inputs.aws-resource-names }}
      run: ruby scripts/scripts/spin_up_ecs.rb expand
      shell: bash
    - if: ${{ inputs.command == 'sample-deploy' }}
      name: Deploy new code to Fargate
      env:
        RESOURCE_NAMES: ${{ inputs.aws-resource-names }}
      run: ruby scripts/scripts/redeploy.rb
      shell: bash
    - if: ${{ inputs.command == 'contract' }}
      name: Spin up ECS task running laridae to contract
      env:
        RESOURCE_NAMES: ${{ inputs.aws-resource-names }}
      run: ruby scripts/scripts/spin_up_ecs.rb contract
      shell: bash
