name: "laridae-postgres-db-schema-migrations"
description: "Expands/contracts db schema laridae and deploys new application code to ECS."
inputs:
  action:
    description: "expand (db schema using laridae) / deploy (new code to Fargate) / contract (db schema using laridae) / full"
    required: true
  aws-access-key-id:
    description: "AWS access key Id"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key"
    required: true
  aws-region:
    description: "AWS region"
    required: true
  aws-resource-names:
    description: "Resource names in AWS"
    required: true
runs:
  using: composite
  steps:
    - if: ${{ inputs.action == 'deploy' || inputs.action == 'full' }}
      name: Check out application code.
      uses: actions/checkout@v4
      with:
        path: repo
    - name: Check out migration script
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          laridae_migration.json
        sparse-checkout-cone-mode: false
        path: migration_script
    - name: Checkout action scripts
      uses: actions/checkout@v4
      with:
        repository: 2308-team-8/laridae-action
        sparse-checkout: |
          scripts
        sparse-checkout-cone-mode: false
        ref: main
        path: scripts
    - name: Authenticate to AWS
      env:
        RESOURCE_NAMES: ${{ inputs.aws-resource-names }}
      run: ruby scripts/scripts/authenticate.rb
      shell: bash
    - if: ${{ inputs.action == 'expand' || inputs.action == 'full' }}
      name: Spin up ECS task running laridae to expand
      env:
        RESOURCE_NAMES: ${{ inputs.aws-resource-names }}
      run: ruby scripts/scripts/spin_up_ecs.rb expand
      shell: bash
    - if: ${{ inputs.action == 'deploy' || inputs.action == 'full'}}
      name: Deploy new code to Fargate
      env:
        RESOURCE_NAMES: ${{ inputs.aws-resource-names }}
      run: ruby scripts/scripts/redeploy.rb
      shell: bash
    - if: ${{ inputs.action == 'contract' || inputs.action == 'full' }}
      name: Spin up ECS task running laridae to contract
      env:
        RESOURCE_NAMES: ${{ inputs.aws-resource-names }}
      run: ruby scripts/scripts/spin_up_ecs.rb contract
      shell: bash
